// components/services/SignalService.js
import axios from 'axios';
import { collection, addDoc, serverTimestamp, query, where, getDocs } from 'firebase/firestore';
import { db, auth } from '../../firebaseConfig';
import * as Notifications from 'expo-notifications';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { CALENDARIFIC_API_KEY, OPENWEATHER_API_KEY, NEWS_API_KEY } from '@env';

class SignalService {
  static async checkAllSources() {
    console.log('🔍 SignalService.checkAllSources called');
    
    const user = auth.currentUser;
    if (!user) {
      console.log('❌ No user logged in');
      return [];
    }

    try {
      console.log('✅ User found, checking sources...');
      const newSignals = [];
      
      // Check all external sources
      const holidays = await this.checkPublicHolidays();
      newSignals.push(...holidays);
      
      const weatherAlerts = await this.checkWeather();
      newSignals.push(...weatherAlerts);
      
      const news = await this.checkIndustryNews();
      newSignals.push(...news);
      
      // Save all new signals to Firestore
      let savedCount = 0;
      for (const signal of newSignals) {
        const saved = await this.saveSignal(signal);
        if (saved) savedCount++;
      }
      
      console.log(`✅ Added ${savedCount} new signals`);
      return newSignals;
    } catch (error) {
      console.error('Error in checkAllSources:', error);
      return [];
    }
  }

  // 1. 🗓️ PUBLIC HOLIDAYS API
  static async checkPublicHolidays() {
    try {
      const year = new Date().getFullYear();
      const country = 'NG'; // Nigeria
      const cacheKey = `@holidays_${country}_${year}`;
      
      // Check cache first
      try {
        const cachedData = await AsyncStorage.getItem(cacheKey);
        if (cachedData) {
          const { timestamp, data } = JSON.parse(cachedData);
          const now = Date.now();
          // Cache for 24 hours (24 * 60 * 60 * 1000)
          if (now - timestamp < 24 * 60 * 60 * 1000) {
            console.log('✅ Using cached holiday data');
            return this.formatHolidays(data);
          }
        }
      } catch (cacheErr) {
        console.log('Cache read error:', cacheErr.message);
      }

      console.log('🌐 Fetching fresh holiday data from API...');
      const response = await axios.get(
        `https://calendarific.com/api/v2/holidays?api_key=${CALENDARIFIC_API_KEY}&country=${country}&year=${year}`
      );
      
      if (!response.data?.response?.holidays) {
        console.log('No holidays data received');
        return [];
      }
      
      const holidays = response.data.response.holidays;
      
      // Save to cache
      try {
        await AsyncStorage.setItem(cacheKey, JSON.stringify({
          timestamp: Date.now(),
          data: holidays
        }));
      } catch (cacheErr) {
        console.log('Cache write error:', cacheErr.message);
      }
      
      return this.formatHolidays(holidays);
    } catch (error) {
      if (error.response?.status === 429) {
        console.log('⚠️ Calendarific rate limit exceeded - will try again later');
      } else {
        console.error('Error fetching holidays:', error.response?.data || error.message);
      }
      return [];
    }
  }

  // Helper: Format holiday data for signals
  static formatHolidays(holidays) {
    const today = new Date();
    const nextMonth = new Date(today);
    nextMonth.setMonth(nextMonth.getMonth() + 1);
    
    const upcomingHolidays = holidays
      .filter(h => h.date?.iso && new Date(h.date.iso) > new Date() && new Date(h.date.iso) < nextMonth)
      .slice(0, 3);
    
    return upcomingHolidays.map(holiday => ({
      title: `🏖️ Holiday: ${holiday.name || 'Public Holiday'}`,
      system: 'External • Holidays',
      type: 'Deadline',
      level: 'Medium',
      detail: `${holiday.name || 'Holiday'} on ${holiday.date?.iso ? new Date(holiday.date.iso).toLocaleDateString() : 'soon'}`,
      trend: 'flat',
      due: holiday.date?.iso ? this.getRelativeDate(holiday.date.iso) : 'Soon',
      source: 'holiday-api',
      externalId: holiday.uuid || `holiday-${Date.now()}-${Math.random()}`,
      autoGenerated: true,
      audience: 'all',
      read: false
    }));
  }

  // 2. 🌦️ WEATHER ALERTS
  static async checkWeather() {
    try {
      const response = await axios.get(
        `https://api.openweathermap.org/data/2.5/weather?q=Lagos&appid=${OPENWEATHER_API_KEY}&units=metric`
      );
      
      const weather = response.data;
      const alerts = [];
      
      if (weather.main?.temp > 35) {
        alerts.push({
          title: '🌡️ Extreme Heat Warning',
          system: 'External • Weather',
          type: 'Risk',
          level: 'Medium',
          detail: `Temperature of ${weather.main.temp}°C expected. Stay hydrated!`,
          trend: 'up',
          due: 'Today',
          source: 'weather-api',
          externalId: `heat-${Date.now()}`,
          autoGenerated: true,
          audience: 'all',
          read: false
        });
      }
      
      if (weather.rain && weather.rain['1h'] > 5) {
        alerts.push({
          title: '🌧️ Rainfall Alert',
          system: 'External • Weather',
          type: 'Risk',
          level: 'Low',
          detail: `${weather.rain['1h']}mm rain expected. Plan for delays.`,
          trend: 'down',
          due: 'Today',
          source: 'weather-api',
          externalId: `rain-${Date.now()}`,
          autoGenerated: true,
          audience: 'all',
          read: false
        });
      }
      
      return alerts;
    } catch (error) {
      if (error.response?.status === 401) {
        console.log('⏳ Weather API key still activating - this is normal');
      } else {
        console.error('Error fetching weather:', error.response?.data || error.message);
      }
      return [];
    }
  }

  // 3. 📰 INDUSTRY NEWS
  static async checkIndustryNews() {
    try {
      const response = await axios.get(
        `https://newsapi.org/v2/everything?q=HR+workplace+management&apiKey=${NEWS_API_KEY}&pageSize=3&sortBy=publishedAt`
      );
      
      if (!response.data?.articles) return [];
      
      return response.data.articles.map((article, index) => ({
        title: `📰 ${article.title?.substring(0, 50) || 'HR News'}...`,
        system: 'External • News',
        type: 'Watch',
        level: 'Low',
        detail: article.description || article.title || 'New industry news available',
        trend: 'flat',
        due: 'Read',
        source: 'news-api',
        externalId: article.url ? `news-${article.url}` : `news-${Date.now()}-${index}`,
        autoGenerated: true,
        audience: 'all',
        read: false
      }));
    } catch (error) {
      console.error('Error fetching news:', error.response?.data || error.message);
      return [];
    }
  }

  // Helper: Save signal to Firestore
  static async saveSignal(signal) {
    const user = auth.currentUser;
    if (!user) return false;
    
    try {
      // Ensure externalId exists
      if (!signal.externalId) {
        signal.externalId = `signal-${Date.now()}-${Math.random()}`;
      }
      
      const signalsRef = collection(db, 'users', user.uid, 'signals');
      const q = query(signalsRef, where('externalId', '==', signal.externalId));
      const existing = await getDocs(q);
      
      if (existing.empty) {
        await addDoc(signalsRef, {
          ...signal,
          createdAt: serverTimestamp(),
        });
        
        if (signal.level === 'High' || signal.type === 'Risk') {
          await this.sendSignalNotification(signal);
        }
        console.log('✅ Signal saved:', signal.title);
        return true;
      }
      return false;
    } catch (error) {
      console.error('Error saving signal:', error);
      return false;
    }
  }

  // Helper: Send notification
  static async sendSignalNotification(signal) {
    try {
      await Notifications.scheduleNotificationAsync({
        content: {
          title: signal.title,
          body: signal.detail,
          data: { type: 'external-signal' },
          sound: true,
        },
        trigger: null,
      });
    } catch (error) {
      console.error('Error sending notification:', error);
    }
  }

  // Helper: Get relative due date
  static getRelativeDate(dateString) {
    try {
      const date = new Date(dateString);
      const today = new Date();
      const diffDays = Math.ceil((date - today) / (1000 * 60 * 60 * 24));
      
      if (diffDays === 0) return 'Today';
      if (diffDays === 1) return 'Tomorrow';
      if (diffDays < 7) return `${diffDays} days`;
      return date.toLocaleDateString();
    } catch (error) {
      return 'Soon';
    }
  }
}

export default SignalService;